# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
license="""(C) Copyright 2020 - QTech Community.
This project is licensed under the CC BY-NC-SA 4.0 license.
See this link for the full license: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
"""

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="http://my.issue.tracker/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]] #mandatory
modId="qforgemod" #mandatory
version="1.1-release1" #mandatory
displayName="QForgeMod: Main Module" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://quintenjungblut.wixsite.com/qplaysoftware/" #optional
#logoFile="qforgemod.png" #optional
credits="Qboi123" #optional
authors="Qboi123" #optional
description='''
§l§nQForgeMod§r
  §7§oProbably just another random things mod.§r

  §7§lStatus:§r §o§aRelease§r

  §oFor some of you, knows the The World Items mod and it's versions 1, 2 and 3.§r
  §oBut now knowing more about creating mods, there's a new new version of the mod with a brand new name.§r
  §oThe mod has been rewritten in pure Java. And adding already more things that before: The QForgeMod Project!§r

§l§nLinks:§r
  §lDiscord server coming soon!§r
  QSoftware home page: https://quintenjungblut.wixsite.com/qplaysoftware

§l§nSource code:§r
  https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fgitlab.com%252fqsoftware2%252fqforgemod

§l§nBugs / Feature requests§r
  §cIn Alpha / Beta releases stuff might change or break, it's recommended to use them for testing purposes only.§r
  If there's a problem with the mod: don't post the crash report in the comments, but post it on the issue tracker here.
  If there's no crash report but it still crashes, post the debug.log file in your .minecraft/logs folder to the issue tracker.
  If there's no crash report and there's no crash in the debug.log, then there's probably a problem with your Java / Computer.

  If you want to request a feature you can also do it here.

§l§nCredits:§r
  §l"Modern Sofa" by JustinRustin (Modern Sofa)§r
  Available for download at https://blockmodels.com/361/ §r

  §l"Club" by Gengar (Club)§r
  §oAvailable for download at https://blockmodels.com/model/496/ §r

  §l"Table with tablecloth" by Miep_HD (Table)§r
  §oAvailable for download at https://blockmodels.com/model/668/ §r

  §l"Healing Potion" by Gengar (Healing Potion)§r
  §oAvailable for download at https://blockmodels.com/model/531/ §r

  §l"Improved PC Gamer" by Giovanni_5656 (Game PC)§r
  §oAvailable for download at https://blockmodels.com/model/339/ §r

  §l"Router" by F1ash (Router)§r
  §oAvailable for download at https://blockmodels.com/model/331/ §r

  §l"Wooden Box" by F1ash (Crate)§r
  §oAvailable for download at https://blockmodels.com/model/330/ §r

  §l"Minecraft Dungeons Textures for Minecraft Java Edition" by Kai1907 and Shadow_236§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/minecraft-dungeons-textures-for-minecraft-java-edition/ §r

  §l"Fresh CIT v1.2" by FreshLX§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/fresh-cit-v1-0/ §r

  §l"GearPlus 1.16!" by Nate the Penguin§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/vanilla-more-items-armor-shields-and-more/ §r

  §l"GearPlus - Terraria Edition" by Nate the Penguin§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/gearplus-terraria-edition/ §r

  §l"Cocoa Cake" by The Sailor§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/cocoa-cake/ §r

  §l"Bone meal into Fertilizer" by Sucro120§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/bone-meal-into-fertilizer/ §r

  §l"ActuallyAssets - Hypixel Skyblock v1.6.6" by MotorGorilla1§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/actuallyassets-hypixel-skyblock-v-10/ §r

  §l"MoobLoom Update(Optifine)" by un_roman§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/moobloom-update/ §r

  §l"Avocados" by kekkman§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/avocados-4860171/ §r

  §l"Vanilla+ | 225 Custom Bookshelves Add-On" by sirkomplete, Etaris and Robert0213§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/vanilla-225-custom-bookshelves-add-on/ §r


§l§nOther Mods:§r
  §l=--------------------------=§r
  §oSilent's Mechanisms§r
  §l§n=--------------------------=§r
  §lGitHub:§r
   §o https://github.com/SilentChaos512/Silents-Mechanisms/tree/f8abec8f42cb0d2e2b799f7b4ff8f17eb33b7e69 §r
  §lCurseForge:§r
   §o https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms §r
  §lCurseForge Download:§r
   §o https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms/files/3105339 §r

  §l=--------------------------=§r
  §oSilent Lib§r
  §l§n=--------------------------=§r
  §lGitHub:§r
   §o https://github.com/SilentChaos512/SilentLib/tree/ef258b04897296131e3e1f439df8b5c1425fc453 §r
  §lCurseForge:§r
   §o https://www.curseforge.com/minecraft/mc-mods/silent-lib §r
  §lCurseForge Download:§r
   §o https://www.curseforge.com/minecraft/mc-mods/silent-lib/files/3103851 §r

  §l=--------------------------=§r
  §oQForgeUtils 1.0§r
  §l§n=--------------------------=§r
  §oDownload not available!§r
'''

[[mods]]
modId="qsilentlib"
version="4.9"
displayName="QForgeMod: Silent Library"
# updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/SilentLib/1.14/update.json"
description='''
    Forked from https://github.com/SilentChaos512/SilentLib/tree/ef258b04897296131e3e1f439df8b5c1425fc453

    Shared library for Silent's mods
    '''
[[mods]] #mandatory
# The modid of the mod
modId="qtexturedmodels" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.0-release1" #mandatory
# A display name for the mod
displayName="QForgeMod: Textured Models Module" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="bc_logo.png" #optional
# A text field displayed in the mod UI
credits="Thanks for many help goes to McJty and the Forge Forum Team" #optional
# A text field displayed in the mod UI
authors="PianoManu, Qboi123" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This Mod is partially forked from: https://github.com/PianoManu/QTextureModels
The mod was merged after the base essentials of QForgeMod were created.

Original description:
Fork Mod of Carpenter's Blocks Mod created by Mineshopper (owner of the idea) for older versions of Minecraft.
I created this fork because friends of mine would like to play this mod on 1.15 (and me too).

Right now there is no guide for this mod, so here is one in small form:
- Right-Click on a frame block to give it the texture of the block you clicked it with
- Right-Click with the hammer to get the block back out of the frame (you can change this feature in the config file, so that you only need an empty hand and Sneak-Rightclick)
- For blocks with different textures on each side, you can select the texture you want using the texture wrench
- Let the blocks glow by right-clicking them with glowstone dust or coal/charcoal
- You can also change the appearance of a block by right-clicking it with the chisel and the paintbrush

Have fun!
'''

[[mods]]
modId="qfilters"
version="1.3.0"
displayName="QForgeMod: Filters Module"
license="""
GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1
https://raw.githubusercontent.com/MrCrayfish/Filters/master/LICENSE.txt

Forked fro here:
"""
logoFile="filters.png"
credits=""
authors="MrCrayfish, Qboi123"
description='''
A mod that improves the Creative GUI by introducing filters based on tags
Ported to 1.16.3 by Qboi123.
'''

[[dependencies.qfilters]] #optional
modId="forge"
mandatory=true
versionRange="[34,)"
ordering="NONE"
side="CLIENT"
[[dependencies.qfilters]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.qtexturedmodels]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[34,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
# Here's another dependency
[[dependencies.qtexturedmodels]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"

# Silent Lib dependencies
[[dependencies.qsilentlib]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="BOTH"
[[dependencies.qsilentlib]]
modId="minecraft"
mandatory=true
versionRange="[1.16.2,)"
ordering="NONE"
side="BOTH"

# QForgeUtils dependencies.
[[dependencies.qforgemod]]
modId="filters"
mandatory=false
versionRange="1.3.0"
ordering="BEFORE"
side="CLIENT"
[[dependencies.qforgemod]]
modId="qsilentlib"
mandatory=true
versionRange="4.9"
ordering="NONE"
side="BOTH"
[[dependencies.qforgemod]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[34,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.qforgemod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"
